DIGIT: 0_9

LETTER: A_Za_z

NT: ACGT..

IDENTIFIER: LETTER (LETTER | DIGIT | '.' | '_')+

REFERENCE: IDENTIFIER (REFERENCE)?

DESCRIPTION: REFERENCE ':' (LETTER '.')? ALLELE

UNKNOWN: '?'

NUMBER: (DIGIT)+

OFFSET: ('+' | '-')? (NUMBER | UNKNOWN)

POINT: ('*' | '-')? (NUMBER | UNKNOWN) (OFFSET)?

UNCERTAIN_POINT: '(' POINT '_' POINT ')'

RANGE: (POINT | UNCERTAIN_POINT) '_' (POINT | UNCERTAIN_POINT)

LOCATION: (POINT | UNCERTAIN_POINT | RANGE)

SEQUENCE: NT+

EXACT_RANGE: (NUMBER | UNKNOWN) '_' (NUMBER | UNKNOWN)

LENGTH: (NUMBER | UNKNOWN | ('(' NUMBER | UNKNOWN | EXACT_RANGE ')'))

REPEAT_NUMBER: (NUMBER | UNKNOWN | EXACT_RANGE)

INSERT: (SEQUENCE | DESCRIPTION | LOCATION | LENGTH) (('inv'? ('[' REPEAT_NUMBER ']')?) | (('[' REPEAT_NUMBER ']')? 'inv'?))?

INSERTED: (('[' (INSERT (';' INSERT)*) ']') | INSERT)

CONVERSION: 'con' INSERTED

DELETION: 'del' (INSERTED)?

DELETION_INSERTION: 'del' (INSERTED)? 'ins' INSERTED

DUPLICATION: 'dup' (INSERTED)?

INSERTION: 'ins' INSERTED

INVERSION: 'inv' (INSERTED)?

SUSTITUTION: (SEQUENCE)? '>' INSERTED

REPEAT: (SEQUENCE '[' REPEAT_NUMBER ']')+

VARIANT: LOCATION (CONVERSION | DELETION | DELETION_INSERTION | DUPLICATION | INSERTION | INVERSION | SUBSTITUTION | REPEAT)?

ALLELE: (('[' ((VARIANT (';' VARIANT)*) | '=') ']') | VARIANT | '=')
