#ifndef HGVS_H
#define HGVS_H


#define HGVS_STRINGIZE2(s) #s
#define HGVS_STRINGIZE(s) HGVS_STRINGIZE2(s)

#define HGVS_VERSION_MAJOR 1
#define HGVS_VERSION_MINOR 0
#define HGVS_VERSION_PATCH 0
#ifdef RELEASE
#define HGVS_VERSION_STRING HGVS_STRINGIZE(HGVS_VERSION_MAJOR) \
"." HGVS_STRINGIZE(HGVS_VERSION_MINOR) \
"." HGVS_STRINGIZE(HGVS_VERSION_PATCH)
#else
#define HGVS_VERSION_STRING HGVS_STRINGIZE(HGVS_VERSION_MAJOR) \
"." HGVS_STRINGIZE(HGVS_VERSION_MINOR) \
"." HGVS_STRINGIZE(HGVS_VERSION_PATCH) \
"-dev"
#endif


#include "hgvs_interface.h"
#include "hgvs_parser.h"


#endif
