name: ci
on: [push]
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - run: sudo apt update
            - run: sudo apt install -y valgrind
            - run: gcc --version
            - run: valgrind --version
            - uses: actions/checkout@v3
            - run: make OPTIONS=ANSI check
